openapi: 3.0.1
info:
  contact:
    email: yasu-abe@u-aizu.ac.jp
    name: Yasuhiro ABE
  description: An example code using the OpenID Connect, OIDC.
  title: A sample OIDC Client
  version: 1.0.0
servers:
- url: https://localhost:8000/
paths:
  /:
    get:
      description: The landing page.
      responses:
        200:
          description: If authenticated, it shows user information.
  /protected:
    get:
      description: Protected contents only authenticated user can view.
      responses:
        200:
          description: If authenticated, it shows user information.
        303:
          description: If not-authenticated, then redirecting to the /login.
  /login:
    get:
      description: The OIDC login entrypoint.
      responses:
        200:
          description: Show the login form.
    post:
      description: OIDC login page
      responses:
        303:
          description: Redirect to the dex oids provider
  /callback:
    get:
      description: |
        The callback endpoint from an OIDC server.
        e.g. /callback?code=xxxx&amp;state=xxxx
      parameters:
      - explode: false
        in: path
        name: code
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: state
        required: true
        schema:
          type: string
        style: simple
      responses:
        303:
          description: Redirect to the top landing page or somewhere.
  /logout:
    get:
      description: The OIDC logout endpoint to clear the session object.
      responses:
        200:
          description: stay on this page.
        303:
          description: redirect to /.
components:
  schemas: {}
