FROM ruby:3.0-alpine as rubydev

RUN apk update && \
    apk add --no-cache tzdata bash ca-certificates \
    	make gcc libc-dev linux-headers build-base patch

COPY . /app
WORKDIR /app

RUN bundle config set path lib
RUN bundle install

## Build runtime
FROM ruby:3.0-alpine

RUN apk update && \
    apk add --no-cache tzdata bash ca-certificates

COPY --from=rubydev /app /app
WORKDIR /app

ENV OIDC_PROVIDER_URI https://example.com/dex
ENV OIDC_CLIENT_ID client-id
ENV OIDC_SECRET 62cfafd6c7d0454852a16e365bce90b0
ENV OIDC_REDIRECT_URI http://localhost:8080/callback
ENV REDIS_URI redis://localhost:6379/0
ENV SINATRA_PORT 8080
EXPOSE $SINATRA_PORT

ADD run.sh /run.sh
RUN chmod +x /run.sh

RUN addgroup sinatra
RUN adduser -S -G sinatra sinatra
USER sinatra
RUN bundle config set path lib

ENTRYPOINT ["/run.sh"]
